version: '3.7'

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: .docker/entrypoint.sh
    volumes:
    - .:/code
    ports:
    - 80:80
    env_file:
      - bomrole/.env