# Generated by Django 3.0.3 on 2020-02-20 23:01

import api.models
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tourist Spot',
                'verbose_name_plural': 'Toutist Spots',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TouristSpotCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='TouristSpotUpvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tourist_spot', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='api.TouristSpot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tourist Spot Upvote',
                'verbose_name_plural': 'Tourist Spot Upvotes',
            },
        ),
        migrations.CreateModel(
            name='TouristSpotsPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('picture', models.ImageField(upload_to=api.models.user_directory_path)),
                ('tourist_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='api.TouristSpot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tourist_spots_pictures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tourist Spot Image',
                'verbose_name_plural': 'Tourist Spot Images',
            },
        ),
        migrations.CreateModel(
            name='TouristSpotComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField(default='', max_length=255)),
                ('tourist_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.TouristSpot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tourist Spot Comment',
                'verbose_name_plural': 'Tourist Spot Comments',
            },
        ),
        migrations.AddField(
            model_name='touristspot',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.TouristSpotCategory'),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tourist_spots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FavoriteTouristSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tourist_spot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TouristSpot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Tourist Spot',
                'verbose_name_plural': 'Favorite Tourist Spots',
            },
        ),
    ]
