# Generated by Django 3.0.3 on 2020-02-08 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('touristspots', '0002_touristspotupvote_tourist_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspotupvote',
            name='tourist_spot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='touristspots.TouristSpot'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tourist Spot Comment',
                'verbose_name_plural': 'Tourist Spot Comments',
            },
        ),
    ]
