# Generated by Django 3.0.3 on 2020-02-08 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touristspots', '0005_auto_20200208_2324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='TouristSpotCategory',
        ),
    ]
