# Generated by Django 3.0.3 on 2020-02-08 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('touristspots', '0007_favoritetouristspot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpotsPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('tourist_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touristspots.TouristSpot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tourist Spot Image',
                'verbose_name_plural': 'Tourist Spot Images',
            },
        ),
    ]
