# Generated by Django 3.0.3 on 2020-02-09 03:44

from django.db import migrations, models
import django.db.models.deletion
import touristspots.models


class Migration(migrations.Migration):

    dependencies = [
        ('touristspots', '0008_touristspotspictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspotspictures',
            name='image',
            field=models.ImageField(default=None, upload_to=touristspots.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='touristspotspictures',
            name='tourist_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='touristspots.TouristSpot'),
        ),
    ]
