# Generated by Django 3.0.3 on 2020-02-09 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('touristspots', '0009_auto_20200209_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touristspotspictures',
            old_name='image',
            new_name='picture',
        ),
        migrations.AlterField(
            model_name='favoritetouristspot',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='touristspotcategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='touristspotcomments',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='touristspotspictures',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='touristspotspictures',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tourist_spots_pictures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='touristspotupvote',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
