# Generated by Django 3.0.3 on 2020-02-11 02:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touristspots', '0010_auto_20200209_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='touristspot',
            name='longitude',
        ),
        migrations.AddField(
            model_name='touristspot',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
