# Generated by Django 3.0.3 on 2020-02-17 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touristspots', '0011_auto_20200211_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspotcomments',
            name='tourist_spot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='touristspots.TouristSpot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='touristspotcomments',
            name='text',
            field=models.TextField(default='', max_length=255),
        ),
    ]
